name: Release
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build-ts
      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  release:
    name: Download dist and release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: JS-DevTools/npm-publish@7f426c9ea8cd6f53975623a350c34e3a3707739c # version 2.2.2
        with:
          token: ${{ secrets.NPM_TOKEN }}
